version: "3"
services:
  database-server:
    image: mysql:8.0
    volumes:
      - './migrations:/migrations'
      - './data:/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    container_name: database-server